spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: javaai2026@gmail.com
    password: "xqgu riev zykv wwew"
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
            required: true
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  application:
    name: app
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    url: jdbc:mysql://localhost:3306/fin_track
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:2006.Harut}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    logging:
      file:
        name: log/FinTrack.log
      logback:
        rollingpolicy:
          file-name-pattern: log/FinTrack-%d{yyyy-MM-dd}.log
          max-history: 30
  task:
    scheduling:
      enabled: true
server:
  port: 8083
